
import React from 'react';
import type { AnalysisResult, UserProfile } from '../utils/analyzer';
import { MapPin, CheckCircle, AlertTriangle } from 'lucide-react';

interface Props {
  profile: UserProfile;
  results: AnalysisResult;
}

const CareerSnapshot: React.FC<Props> = ({ profile, results }) => {
  const { topPathways, scorecard } = results;
  const bestPathway = topPathways[0];

  return (
    <div className="max-w-4xl mx-auto bg-white shadow-xl rounded-none border border-gray-200 min-h-[1000px] overflow-hidden">
      {/* Resume Header */}
      <div className="bg-slate-800 text-white p-8">
        <div className="flex justify-between items-start">
          <div>
            <h1 className="text-3xl font-bold mb-2">My Career Snapshot</h1>
            <p className="text-slate-300">Generated by WhatNext</p>
          </div>
          <div className="text-right text-sm text-slate-300 space-y-1">
            <div className="flex items-center justify-end gap-2">
              <span>whatnext-project.web.app</span> <MapPin size={14} />
            </div>
            <div className="flex items-center justify-end gap-2">
               {new Date().toLocaleDateString()}
            </div>
          </div>
        </div>
      </div>

      <div className="p-8 grid grid-cols-3 gap-8">

        {/* Left Column: Profile & Skills */}
        <div className="col-span-1 border-r pr-8 border-gray-100">
          <section className="mb-8">
             <h3 className="text-sm font-bold text-gray-900 uppercase tracking-wider mb-4 border-b pb-2">Profile Overview</h3>
             <ul className="space-y-3 text-sm text-gray-600">
                {scorecard.labels.map((label, idx) => (
                    <li key={label} className="flex justify-between">
                        <span>{label} Points</span>
                        <span className="font-semibold text-gray-800">{scorecard.data[idx]}</span>
                    </li>
                ))}
             </ul>
          </section>

          <section className="mb-8">
             <h3 className="text-sm font-bold text-gray-900 uppercase tracking-wider mb-4 border-b pb-2">Top Skills</h3>
             <div className="flex flex-wrap gap-2">
                {profile.Skills.filter(s => s.text).slice(0, 10).map(s => (
                    <span key={s.id} className="bg-gray-100 text-gray-700 px-2 py-1 rounded text-xs">
                        {s.text}
                    </span>
                ))}
                {profile.Skills.length === 0 && <span className="text-xs text-gray-400">No skills listed</span>}
             </div>
          </section>

          <section>
             <h3 className="text-sm font-bold text-gray-900 uppercase tracking-wider mb-4 border-b pb-2">Interests</h3>
             <div className="flex flex-wrap gap-2">
                {profile.Interests.filter(i => i.text).slice(0, 10).map(i => (
                    <span key={i.id} className="bg-blue-50 text-blue-700 px-2 py-1 rounded text-xs">
                        {i.text}
                    </span>
                ))}
             </div>
          </section>
        </div>

        {/* Right Column: Career Path & Action Plan */}
        <div className="col-span-2">
           <section className="mb-8">
              <h3 className="text-sm font-bold text-blue-600 uppercase tracking-wider mb-4 border-b pb-2 flex items-center gap-2">
                <CheckCircle size={16} /> Recommended Career Path
              </h3>

              {bestPathway ? (
                  <div className="bg-blue-50 p-4 rounded-lg border border-blue-100">
                      <h2 className="text-2xl font-bold text-gray-900 mb-2">{bestPathway.title}</h2>
                      <p className="text-gray-700 mb-3 text-sm">{bestPathway.description}</p>

                      <div className="grid grid-cols-2 gap-4 text-sm mb-3">
                          <div>
                              <span className="text-gray-500 block text-xs">Match Score</span>
                              <span className="font-bold text-blue-700">{bestPathway.matchScore}%</span>
                          </div>
                          <div>
                              <span className="text-gray-500 block text-xs">Potential</span>
                              <span className="font-bold text-green-700">{bestPathway.earningPotential}</span>
                          </div>
                      </div>
                  </div>
              ) : (
                  <p className="text-gray-500 text-sm">No exact match found based on current profile.</p>
              )}
           </section>

           {bestPathway && (
             <>
                <section className="mb-8">
                    <h3 className="text-sm font-bold text-gray-900 uppercase tracking-wider mb-4 border-b pb-2">Gap Analysis</h3>
                    {bestPathway.missingSkills.length > 0 ? (
                        <div className="space-y-2">
                            <p className="text-sm text-gray-600 mb-2">Acquiring these skills will significantly increase your success rate:</p>
                            {bestPathway.missingSkills.map(skill => (
                                <div key={skill} className="flex items-center gap-2 text-sm text-red-600">
                                    <AlertTriangle size={14} />
                                    <span>{skill}</span>
                                </div>
                            ))}
                        </div>
                    ) : (
                        <p className="text-sm text-green-600 flex items-center gap-2">
                            <CheckCircle size={14} /> You have all the required skills for this path!
                        </p>
                    )}
                </section>

                <section>
                    <h3 className="text-sm font-bold text-gray-900 uppercase tracking-wider mb-4 border-b pb-2">Immediate Next Steps</h3>
                    <div className="space-y-4">
                        {bestPathway.roadmap.map((step, i) => (
                            <div key={i} className="flex items-start gap-3">
                                <div className="bg-slate-800 text-white rounded-full w-6 h-6 flex items-center justify-center flex-shrink-0 text-xs mt-0.5">
                                    {i + 1}
                                </div>
                                <p className="text-sm text-gray-700">{step}</p>
                            </div>
                        ))}
                    </div>
                </section>
             </>
           )}
        </div>
      </div>

      {/* Footer */}
      <div className="bg-gray-50 p-8 text-center text-xs text-gray-500 border-t border-gray-200 mt-auto">
        This document is an automatically generated snapshot of your current career potential based on the WhatNext analysis model.
      </div>
    </div>
  );
};

export default CareerSnapshot;
