
import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';
import type { AnalysisResult, UserProfile } from './analyzer';

export const generatePDF = (results: AnalysisResult, profile: UserProfile) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.width;

  // --- Title & Branding ---
  doc.setFontSize(22);
  doc.setTextColor(41, 128, 185); // Blue color
  doc.text('WhatNext – Key To Find Success', pageWidth / 2, 20, { align: 'center' });

  doc.setFontSize(12);
  doc.setTextColor(100);
  doc.text('Personalized Career & Earning Roadmap', pageWidth / 2, 30, { align: 'center' });

  doc.line(10, 35, pageWidth - 10, 35); // Separator line

  // --- Profile Summary ---
  doc.setFontSize(16);
  doc.setTextColor(0);
  doc.text('Profile Summary', 14, 45);

  const profileData = [
    ['Category', 'Key Inputs'],
    ['Education', profile.Education.map(i => i.text).join(', ') || 'N/A'],
    ['Skills', profile.Skills.map(i => i.text).join(', ') || 'N/A'],
    ['Hobbies', profile.Hobbies.map(i => i.text).join(', ') || 'N/A'],
    ['Interests', profile.Interests.map(i => i.text).join(', ') || 'N/A'],
    ['Activities', profile.Activities.map(i => i.text).join(', ') || 'N/A'],
    ['Spending', profile.Spending.map(i => i.text).join(', ') || 'N/A'],
    ['Resources', profile.Resources.map(i => i.text).join(', ') || 'N/A'],
  ];

  autoTable(doc, {
    startY: 50,
    head: [profileData[0]],
    body: profileData.slice(1),
    theme: 'grid',
    headStyles: { fillColor: [41, 128, 185] },
    columnStyles: { 0: { fontStyle: 'bold', cellWidth: 40 } },
  });

  // --- Top Opportunities ---
  const finalY = (doc as any).lastAutoTable.finalY || 150;
  doc.setFontSize(16);
  doc.text('Top Earning Pathways', 14, finalY + 15);

  const opportunitiesData = results.topPathways.slice(0, 5).map(p => [
    p.title,
    `${p.matchScore}%`,
    p.difficulty,
    p.timeframe,
    p.earningPotential
  ]);

  autoTable(doc, {
    startY: finalY + 20,
    head: [['Pathway', 'Match', 'Level', 'Timeline', 'Potential']],
    body: opportunitiesData,
    theme: 'striped',
    headStyles: { fillColor: [46, 204, 113] },
  });

  // --- Action Plan (Top 2) ---
  let currentY = (doc as any).lastAutoTable.finalY + 15;

  // Check page break
  if (currentY > 250) {
    doc.addPage();
    currentY = 20;
  }

  doc.setFontSize(16);
  doc.text('Detailed Action Plan', 14, currentY);
  currentY += 10;

  results.topPathways.slice(0, 2).forEach((pathway, index) => {
    if (currentY > 250) {
        doc.addPage();
        currentY = 20;
    }

    doc.setFontSize(14);
    doc.setTextColor(41, 128, 185);
    doc.text(`${index + 1}. ${pathway.title}`, 14, currentY);
    currentY += 7;

    doc.setFontSize(11);
    doc.setTextColor(0);
    doc.text(`Readiness: ${pathway.readiness}`, 14, currentY);
    currentY += 7;

    // Roadmap Steps
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.text('Roadmap:', 14, currentY);
    currentY += 5;
    doc.setFont('helvetica', 'normal');

    pathway.roadmap.forEach(step => {
        doc.text(`• ${step}`, 20, currentY);
        currentY += 5;
    });

    // Improvement Steps
    if (pathway.improvementSteps.length > 0) {
        currentY += 2;
        doc.setFont('helvetica', 'bold');
        doc.text('Next Steps for Growth:', 14, currentY);
        currentY += 5;
        doc.setFont('helvetica', 'normal');
        pathway.improvementSteps.forEach(step => {
            // Text wrapping for long steps
            const splitText = doc.splitTextToSize(`• ${step}`, 170);
            doc.text(splitText, 20, currentY);
            currentY += (splitText.length * 5);
        });
    }

    currentY += 10;
  });

  // --- Footer ---
  const totalPages = doc.getNumberOfPages();
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(10);
    doc.setTextColor(150);
    doc.text('Generated by WhatNext - Your Career Compass', pageWidth / 2, 290, { align: 'center' });
  }

  // Download
  doc.save('WhatNext_Career_Report.pdf');
};
